apiVersion: apps/v1
kind: Deployment
metadata:
  name: date-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: date-app
  template:
    metadata:
      labels:
        app: date-app
    spec:
      containers:
        - name: date-app
          image: juholehtimaki/date-app:firsttry
